--
-- PostgreSQL database dump
--

-- Dumped from database version 16.8 (Ubuntu 16.8-0ubuntu0.24.04.1)
-- Dumped by pg_dump version 16.8 (Ubuntu 16.8-0ubuntu0.24.04.1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: usuario; Type: TABLE; Schema: public; Owner: fernando
--

CREATE TABLE public.usuario (
    id bigint NOT NULL,
    nombre character varying(50) NOT NULL,
    email character varying(50) NOT NULL,
    password character varying(250) NOT NULL,
    apellido character varying(50) NOT NULL
);


ALTER TABLE public.usuario OWNER TO fernando;

--
-- Name: Usuario_id_seq; Type: SEQUENCE; Schema: public; Owner: fernando
--

CREATE SEQUENCE public."Usuario_id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public."Usuario_id_seq" OWNER TO fernando;

--
-- Name: Usuario_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: fernando
--

ALTER SEQUENCE public."Usuario_id_seq" OWNED BY public.usuario.id;


--
-- Name: comentario; Type: TABLE; Schema: public; Owner: fernando
--

CREATE TABLE public.comentario (
    id bigint NOT NULL,
    contenido character varying(1000),
    created_at timestamp(6) without time zone,
    fecha timestamp(6) without time zone NOT NULL,
    img character varying(255),
    updated_at timestamp(6) without time zone,
    usuario_id bigint NOT NULL,
    post_id bigint
);


ALTER TABLE public.comentario OWNER TO fernando;

--
-- Name: comentario_id_seq; Type: SEQUENCE; Schema: public; Owner: fernando
--

ALTER TABLE public.comentario ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.comentario_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: evento; Type: TABLE; Schema: public; Owner: fernando
--

CREATE TABLE public.evento (
    id bigint NOT NULL,
    descripcion character varying(250) NOT NULL,
    fecha date NOT NULL,
    nombre character varying(50) NOT NULL,
    ubicacion character varying(250) NOT NULL
);


ALTER TABLE public.evento OWNER TO fernando;

--
-- Name: evento_id_seq; Type: SEQUENCE; Schema: public; Owner: fernando
--

ALTER TABLE public.evento ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.evento_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: grupo; Type: TABLE; Schema: public; Owner: fernando
--

CREATE TABLE public.grupo (
    id bigint NOT NULL,
    nombre character varying(255) NOT NULL,
    descripcion character varying(255) NOT NULL
);


ALTER TABLE public.grupo OWNER TO fernando;

--
-- Name: grupo_id_seq; Type: SEQUENCE; Schema: public; Owner: fernando
--

CREATE SEQUENCE public.grupo_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.grupo_id_seq OWNER TO fernando;

--
-- Name: grupo_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: fernando
--

ALTER SEQUENCE public.grupo_id_seq OWNED BY public.grupo.id;


--
-- Name: mascota; Type: TABLE; Schema: public; Owner: fernando
--

CREATE TABLE public.mascota (
    id bigint NOT NULL,
    genero character varying(5) NOT NULL,
    nombre character varying(50) NOT NULL,
    raza character varying(50) NOT NULL,
    usuario_id bigint NOT NULL
);


ALTER TABLE public.mascota OWNER TO fernando;

--
-- Name: mascota_id_seq; Type: SEQUENCE; Schema: public; Owner: fernando
--

ALTER TABLE public.mascota ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.mascota_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: notificaciones; Type: TABLE; Schema: public; Owner: fernando
--

CREATE TABLE public.notificaciones (
    id bigint NOT NULL,
    fecha date NOT NULL
);


ALTER TABLE public.notificaciones OWNER TO fernando;

--
-- Name: notificaciones_id_seq; Type: SEQUENCE; Schema: public; Owner: fernando
--

ALTER TABLE public.notificaciones ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.notificaciones_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: perfil; Type: TABLE; Schema: public; Owner: fernando
--

CREATE TABLE public.perfil (
    id bigint NOT NULL,
    usuario_id bigint NOT NULL,
    descripcion character varying(255),
    fecha_nacimiento date,
    img character varying(255)
);


ALTER TABLE public.perfil OWNER TO fernando;

--
-- Name: perfil_id_seq; Type: SEQUENCE; Schema: public; Owner: fernando
--

CREATE SEQUENCE public.perfil_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.perfil_id_seq OWNER TO fernando;

--
-- Name: perfil_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: fernando
--

ALTER SEQUENCE public.perfil_id_seq OWNED BY public.perfil.id;


--
-- Name: post; Type: TABLE; Schema: public; Owner: fernando
--

CREATE TABLE public.post (
    id bigint NOT NULL,
    grupo_id bigint,
    creador_id bigint NOT NULL,
    contenido character varying(255),
    fecha timestamp(6) without time zone NOT NULL,
    img text,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone
);


ALTER TABLE public.post OWNER TO fernando;

--
-- Name: post_id_seq; Type: SEQUENCE; Schema: public; Owner: fernando
--

CREATE SEQUENCE public.post_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.post_id_seq OWNER TO fernando;

--
-- Name: post_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: fernando
--

ALTER SEQUENCE public.post_id_seq OWNED BY public.post.id;


--
-- Name: seguido; Type: TABLE; Schema: public; Owner: fernando
--

CREATE TABLE public.seguido (
    id bigint NOT NULL,
    usuario_que_es_seguido_id bigint NOT NULL,
    usuario_que_sigue_id bigint NOT NULL
);


ALTER TABLE public.seguido OWNER TO fernando;

--
-- Name: seguido_id_seq; Type: SEQUENCE; Schema: public; Owner: fernando
--

ALTER TABLE public.seguido ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.seguido_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: usuario_grupo; Type: TABLE; Schema: public; Owner: fernando
--

CREATE TABLE public.usuario_grupo (
    id bigint NOT NULL,
    grupo_id bigint,
    usuario_id bigint NOT NULL,
    rol character varying(255)
);


ALTER TABLE public.usuario_grupo OWNER TO fernando;

--
-- Name: usuario_grupo_id_seq; Type: SEQUENCE; Schema: public; Owner: fernando
--

CREATE SEQUENCE public.usuario_grupo_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.usuario_grupo_id_seq OWNER TO fernando;

--
-- Name: usuario_grupo_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: fernando
--

ALTER SEQUENCE public.usuario_grupo_id_seq OWNED BY public.usuario_grupo.id;


--
-- Name: valoracion; Type: TABLE; Schema: public; Owner: fernando
--

CREATE TABLE public.valoracion (
    id bigint NOT NULL,
    contenido character varying(1000),
    created_at timestamp(6) without time zone,
    fecha timestamp(6) without time zone NOT NULL,
    img character varying(255),
    updated_at timestamp(6) without time zone,
    usuario_id bigint NOT NULL,
    post_id bigint
);


ALTER TABLE public.valoracion OWNER TO fernando;

--
-- Name: valoracion_id_seq; Type: SEQUENCE; Schema: public; Owner: fernando
--

ALTER TABLE public.valoracion ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.valoracion_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: grupo id; Type: DEFAULT; Schema: public; Owner: fernando
--

ALTER TABLE ONLY public.grupo ALTER COLUMN id SET DEFAULT nextval('public.grupo_id_seq'::regclass);


--
-- Name: perfil id; Type: DEFAULT; Schema: public; Owner: fernando
--

ALTER TABLE ONLY public.perfil ALTER COLUMN id SET DEFAULT nextval('public.perfil_id_seq'::regclass);


--
-- Name: post id; Type: DEFAULT; Schema: public; Owner: fernando
--

ALTER TABLE ONLY public.post ALTER COLUMN id SET DEFAULT nextval('public.post_id_seq'::regclass);


--
-- Name: usuario id; Type: DEFAULT; Schema: public; Owner: fernando
--

ALTER TABLE ONLY public.usuario ALTER COLUMN id SET DEFAULT nextval('public."Usuario_id_seq"'::regclass);


--
-- Name: usuario_grupo id; Type: DEFAULT; Schema: public; Owner: fernando
--

ALTER TABLE ONLY public.usuario_grupo ALTER COLUMN id SET DEFAULT nextval('public.usuario_grupo_id_seq'::regclass);


--
-- Data for Name: comentario; Type: TABLE DATA; Schema: public; Owner: fernando
--

COPY public.comentario (id, contenido, created_at, fecha, img, updated_at, usuario_id, post_id) FROM stdin;
\.


--
-- Data for Name: evento; Type: TABLE DATA; Schema: public; Owner: fernando
--

COPY public.evento (id, descripcion, fecha, nombre, ubicacion) FROM stdin;
\.


--
-- Data for Name: grupo; Type: TABLE DATA; Schema: public; Owner: fernando
--

COPY public.grupo (id, nombre, descripcion) FROM stdin;
\.


--
-- Data for Name: mascota; Type: TABLE DATA; Schema: public; Owner: fernando
--

COPY public.mascota (id, genero, nombre, raza, usuario_id) FROM stdin;
\.


--
-- Data for Name: notificaciones; Type: TABLE DATA; Schema: public; Owner: fernando
--

COPY public.notificaciones (id, fecha) FROM stdin;
\.


--
-- Data for Name: perfil; Type: TABLE DATA; Schema: public; Owner: fernando
--

COPY public.perfil (id, usuario_id, descripcion, fecha_nacimiento, img) FROM stdin;
1	1	Hola, me llamo fernando y estoy desarollando esto	1997-03-10	https://lh3.googleusercontent.com/a/ACg8ocJh-1G_Vs8xegmv-8oTwwWAQ3zT-JX2frK4e9Q54ChIZYQg1yw=s288-c-no
3	1	Hola, me llamo Yago y estoy desarollando esto	1997-03-10	https://lh3.googleusercontent.com/a/ACg8ocJh-1G_Vs8xegmv-8oTwwWAQ3zT-JX2frK4e9Q54ChIZYQg1yw=s288-c-no
\.


--
-- Data for Name: post; Type: TABLE DATA; Schema: public; Owner: fernando
--

COPY public.post (id, grupo_id, creador_id, contenido, fecha, img, created_at, updated_at) FROM stdin;
4	\N	1	Este es mi gato luco.	2025-04-11 15:58:50.486669	https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcQd1kWKsODGmz1P44kiLTfpeIOkaemYITnaRVOZEn372xCyrpNoQQ_dMDAV4dWLpVTDFekNEtlkJaDnhlTzoQWdNg	2025-04-11 15:58:50.614697	2025-04-11 15:58:50.614909
3	\N	1	El retrato de POPI.	2025-04-10 20:38:08.37809	https://images.pexels.com/photos/1851164/pexels-photo-1851164.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1	2025-04-10 20:38:08.427828	2025-04-11 16:15:45.33574
1	\N	1	Este es un nuevo post	2025-04-01 00:00:00	https://images.pexels.com/photos/45170/kittens-cat-cat-puppy-rush-45170.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1	\N	2025-04-11 16:16:22.485728
2	\N	1	Hoy tuvimos una caminata con los perritos del refugio (PRUEBA)	2025-04-10 18:31:33.409983	https://images.pexels.com/photos/33287/dog-viszla-close.jpg?auto=compress&cs=tinysrgb&w=600	2025-04-10 18:31:33.437484	2025-04-11 16:17:47.107813
5	\N	3	Paseando a mi gato.	2025-04-11 16:26:38.988433	https://scontent-mad2-1.xx.fbcdn.net/v/t39.30808-6/464555325_8558598987522595_4024770004962422813_n.jpg?_nc_cat=110&ccb=1-7&_nc_sid=127cfc&_nc_ohc=urpUzOvrTIIQ7kNvwH9w2MW&_nc_oc=AdmWqo6UZymyM9_lrUY5ZC_UBW0z5dmzG3By-pdiAYoOO6-mOwudBYOetMVrSX8iH18&_nc_zt=23&_nc_ht=scontent-mad2-1.xx&_nc_gid=9oynF_w7A0JJmPoZUjwVoA&oh=00_AfHFtKyEPZTKOC9NHzDCPWmKGjeSiJhBwNfXQPXZnVH9vw&oe=67FEF35E	2025-04-11 16:26:38.989125	2025-04-11 16:26:38.989153
8	\N	1	Lo que vimos hoy en el parque.	2025-04-11 17:48:29.542252	https://images.pexels.com/photos/460775/pexels-photo-460775.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1	2025-04-11 17:48:29.561819	2025-04-11 17:48:29.561958
9	\N	3	Nuevo miembro en la familia.2	2025-04-11 19:16:32.224763	https://images.pexels.com/photos/59523/pexels-photo-59523.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1	2025-04-11 19:16:32.259106	2025-04-11 19:16:32.259172
\.


--
-- Data for Name: seguido; Type: TABLE DATA; Schema: public; Owner: fernando
--

COPY public.seguido (id, usuario_que_es_seguido_id, usuario_que_sigue_id) FROM stdin;
\.


--
-- Data for Name: usuario; Type: TABLE DATA; Schema: public; Owner: fernando
--

COPY public.usuario (id, nombre, email, password, apellido) FROM stdin;
8	Prueba	Prueba@ejemplo.com	$2a$10$qEdrO.My/Z0FSNUm/QC4NODH6wWU.PtPwtwPtskoLdiYGHtE3xfdC	Prueba
6	Mouad	mouad10@gmail.com	$2a$10$qEdrO.My/Z0FSNUm/QC4NODH6wWU.PtPwtwPtskoLdiYGHtE3xfdC	sedjari
5	Mouad	mouad@gmail.com	$2a$10$qEdrO.My/Z0FSNUm/QC4NODH6wWU.PtPwtwPtskoLdiYGHtE3xfdC	sedjari
4	Test	test@test.com	$2a$10$qEdrO.My/Z0FSNUm/QC4NODH6wWU.PtPwtwPtskoLdiYGHtE3xfdC	User
3	Mouad	msedjari@elpuig.xeill.net	$2a$10$qEdrO.My/Z0FSNUm/QC4NODH6wWU.PtPwtwPtskoLdiYGHtE3xfdC	Sedjari
1	Fernando	fdiaz@1997@gmail.com	$2a$10$qEdrO.My/Z0FSNUm/QC4NODH6wWU.PtPwtwPtskoLdiYGHtE3xfdC	Diaz
10	fer	fer@ejemplo.com	$2a$10$ZcMmd6K/1NLPnVE35qAHDuuro9LAMnsY5caj/k7SB99qFTJHzDOVq	fer
11	yago	yago2@ejemplo.com	$2a$10$ymA1X9.d2t1e4Y36yVQ4meJuKQmMvWrY8UmVu69oIl1wsoOxpQduC	yago
\.


--
-- Data for Name: usuario_grupo; Type: TABLE DATA; Schema: public; Owner: fernando
--

COPY public.usuario_grupo (id, grupo_id, usuario_id, rol) FROM stdin;
\.


--
-- Data for Name: valoracion; Type: TABLE DATA; Schema: public; Owner: fernando
--

COPY public.valoracion (id, contenido, created_at, fecha, img, updated_at, usuario_id, post_id) FROM stdin;
\.


--
-- Name: Usuario_id_seq; Type: SEQUENCE SET; Schema: public; Owner: fernando
--

SELECT pg_catalog.setval('public."Usuario_id_seq"', 11, true);


--
-- Name: comentario_id_seq; Type: SEQUENCE SET; Schema: public; Owner: fernando
--

SELECT pg_catalog.setval('public.comentario_id_seq', 1, false);


--
-- Name: evento_id_seq; Type: SEQUENCE SET; Schema: public; Owner: fernando
--

SELECT pg_catalog.setval('public.evento_id_seq', 1, false);


--
-- Name: grupo_id_seq; Type: SEQUENCE SET; Schema: public; Owner: fernando
--

SELECT pg_catalog.setval('public.grupo_id_seq', 1, false);


--
-- Name: mascota_id_seq; Type: SEQUENCE SET; Schema: public; Owner: fernando
--

SELECT pg_catalog.setval('public.mascota_id_seq', 1, false);


--
-- Name: notificaciones_id_seq; Type: SEQUENCE SET; Schema: public; Owner: fernando
--

SELECT pg_catalog.setval('public.notificaciones_id_seq', 1, false);


--
-- Name: perfil_id_seq; Type: SEQUENCE SET; Schema: public; Owner: fernando
--

SELECT pg_catalog.setval('public.perfil_id_seq', 3, true);


--
-- Name: post_id_seq; Type: SEQUENCE SET; Schema: public; Owner: fernando
--

SELECT pg_catalog.setval('public.post_id_seq', 9, true);


--
-- Name: seguido_id_seq; Type: SEQUENCE SET; Schema: public; Owner: fernando
--

SELECT pg_catalog.setval('public.seguido_id_seq', 1, false);


--
-- Name: usuario_grupo_id_seq; Type: SEQUENCE SET; Schema: public; Owner: fernando
--

SELECT pg_catalog.setval('public.usuario_grupo_id_seq', 1, false);


--
-- Name: valoracion_id_seq; Type: SEQUENCE SET; Schema: public; Owner: fernando
--

SELECT pg_catalog.setval('public.valoracion_id_seq', 1, false);


--
-- Name: usuario Usuario_pkey; Type: CONSTRAINT; Schema: public; Owner: fernando
--

ALTER TABLE ONLY public.usuario
    ADD CONSTRAINT "Usuario_pkey" PRIMARY KEY (id);


--
-- Name: comentario comentario_pkey; Type: CONSTRAINT; Schema: public; Owner: fernando
--

ALTER TABLE ONLY public.comentario
    ADD CONSTRAINT comentario_pkey PRIMARY KEY (id);


--
-- Name: evento evento_pkey; Type: CONSTRAINT; Schema: public; Owner: fernando
--

ALTER TABLE ONLY public.evento
    ADD CONSTRAINT evento_pkey PRIMARY KEY (id);


--
-- Name: grupo grupo_pkey; Type: CONSTRAINT; Schema: public; Owner: fernando
--

ALTER TABLE ONLY public.grupo
    ADD CONSTRAINT grupo_pkey PRIMARY KEY (id);


--
-- Name: mascota mascota_pkey; Type: CONSTRAINT; Schema: public; Owner: fernando
--

ALTER TABLE ONLY public.mascota
    ADD CONSTRAINT mascota_pkey PRIMARY KEY (id);


--
-- Name: notificaciones notificaciones_pkey; Type: CONSTRAINT; Schema: public; Owner: fernando
--

ALTER TABLE ONLY public.notificaciones
    ADD CONSTRAINT notificaciones_pkey PRIMARY KEY (id);


--
-- Name: perfil perfil_pkey; Type: CONSTRAINT; Schema: public; Owner: fernando
--

ALTER TABLE ONLY public.perfil
    ADD CONSTRAINT perfil_pkey PRIMARY KEY (id);


--
-- Name: post post_pkey; Type: CONSTRAINT; Schema: public; Owner: fernando
--

ALTER TABLE ONLY public.post
    ADD CONSTRAINT post_pkey PRIMARY KEY (id);


--
-- Name: seguido seguido_pkey; Type: CONSTRAINT; Schema: public; Owner: fernando
--

ALTER TABLE ONLY public.seguido
    ADD CONSTRAINT seguido_pkey PRIMARY KEY (id);


--
-- Name: usuario_grupo usuario_grupo_pkey; Type: CONSTRAINT; Schema: public; Owner: fernando
--

ALTER TABLE ONLY public.usuario_grupo
    ADD CONSTRAINT usuario_grupo_pkey PRIMARY KEY (id);


--
-- Name: valoracion valoracion_pkey; Type: CONSTRAINT; Schema: public; Owner: fernando
--

ALTER TABLE ONLY public.valoracion
    ADD CONSTRAINT valoracion_pkey PRIMARY KEY (id);


--
-- Name: comentario fk60bfn81srdehm7d381w167d6m; Type: FK CONSTRAINT; Schema: public; Owner: fernando
--

ALTER TABLE ONLY public.comentario
    ADD CONSTRAINT fk60bfn81srdehm7d381w167d6m FOREIGN KEY (post_id) REFERENCES public.grupo(id);


--
-- Name: valoracion fk9n4htv6h6qda5rsg5mq1462; Type: FK CONSTRAINT; Schema: public; Owner: fernando
--

ALTER TABLE ONLY public.valoracion
    ADD CONSTRAINT fk9n4htv6h6qda5rsg5mq1462 FOREIGN KEY (usuario_id) REFERENCES public.usuario(id);


--
-- Name: post fk_creador; Type: FK CONSTRAINT; Schema: public; Owner: fernando
--

ALTER TABLE ONLY public.post
    ADD CONSTRAINT fk_creador FOREIGN KEY (creador_id) REFERENCES public.usuario(id) ON DELETE CASCADE;


--
-- Name: post fk_grupo; Type: FK CONSTRAINT; Schema: public; Owner: fernando
--

ALTER TABLE ONLY public.post
    ADD CONSTRAINT fk_grupo FOREIGN KEY (grupo_id) REFERENCES public.grupo(id) ON DELETE CASCADE;


--
-- Name: usuario_grupo fk_grupo; Type: FK CONSTRAINT; Schema: public; Owner: fernando
--

ALTER TABLE ONLY public.usuario_grupo
    ADD CONSTRAINT fk_grupo FOREIGN KEY (grupo_id) REFERENCES public.grupo(id) ON DELETE CASCADE;


--
-- Name: perfil fk_perfil_usuario; Type: FK CONSTRAINT; Schema: public; Owner: fernando
--

ALTER TABLE ONLY public.perfil
    ADD CONSTRAINT fk_perfil_usuario FOREIGN KEY (usuario_id) REFERENCES public.usuario(id) ON DELETE CASCADE;


--
-- Name: usuario_grupo fk_usuario; Type: FK CONSTRAINT; Schema: public; Owner: fernando
--

ALTER TABLE ONLY public.usuario_grupo
    ADD CONSTRAINT fk_usuario FOREIGN KEY (usuario_id) REFERENCES public.usuario(id) ON DELETE CASCADE;


--
-- Name: valoracion fkg0bhcwrynk7gl1nwqh6w3968w; Type: FK CONSTRAINT; Schema: public; Owner: fernando
--

ALTER TABLE ONLY public.valoracion
    ADD CONSTRAINT fkg0bhcwrynk7gl1nwqh6w3968w FOREIGN KEY (post_id) REFERENCES public.grupo(id);


--
-- Name: comentario fkixspmid2pb85o8ypsd20jakxg; Type: FK CONSTRAINT; Schema: public; Owner: fernando
--

ALTER TABLE ONLY public.comentario
    ADD CONSTRAINT fkixspmid2pb85o8ypsd20jakxg FOREIGN KEY (usuario_id) REFERENCES public.usuario(id);


--
-- PostgreSQL database dump complete
--

